repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        files: ^recipe/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: trailing-whitespace
        files: ^recipe/
      - id: end-of-file-fixer
        files: ^recipe/
      - id: mixed-line-ending
        files: ^recipe/
        args: ['--fix=auto']
